blank_issues_enabled: false
contact_links:
  - name: Say thanks!
    url: https://github.community/
    about: A deep-link to our 'Thank you' issue [by appending `#partial-timeline` to the end of an issue URL]
    
